[package]
name = "actor_macro_app"
version = "0.1.0"
edition = "2024"

[dependencies]
actor_macro_lib = { path = "../actor_macro_lib" }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full", "macros", "rt-multi-thread"] }
